- .travis.yml
Let's see how Travis works compared to drone.io.
> Adding initial travis.yml file.

- README.md
> Adding travis badge.

- README.md
> closes stuphlabs/pullcord#5

- README.md
- conditional.go
- conditional_test.go
Adds the conditional filter (and a reminder of how to run the tests).
> Closes #23

- cookiemask_test.go
- minsession.go
- minsession_test.go
> Closes #42

- .travis.yml
- conditional.go
- cookiemask.go
- landing.go
- minsession.go
- passthru.go
- syslog.go
Adds syslog-based logging using a single private log object shared within the package.
> Closes #48

- cookiemask_test.go
> Closes #54

- trigger/shelltrigger.go
- trigger/shelltrigger_test.go
- trigger/trigger.go
Adds a simplistic shell-based trigger system. Again, probably not production worthy, but a start.
Reviewers: @michaelbeam  @loslosbaby
> Closes #26

- authentication/inmempwdstore.go
> Closes #67

- .travis/install.sh
- authentication/login_handler.go
- authentication/login_handler_test.go
Reviewers:
This adds the login handler for the proof of concept version of Pullcord. The code is rather dirty, but it does seem to work.
> Closes #28 - Adding the proof of concept login handler.

- monitor/minmonitor.go
- monitor/minmonitor_test.go
Reviewers:
Adding MonitorFilter as a stop-gap until the Monitor refactorring.
> Closes #79 - Adds MonitorFilter

- trigger/compound.go
- trigger/compound_test.go
Reviewers:
Adding very basic CompoundTrigger.
> Closes #80 - Adding very basic CompoundTrigger.

- trigger/ratelimit.go
- trigger/ratelimit_test.go
Reviewers:
Adding RateLimitTrigger.
> Closes #84 - Adding RateLimitTrigger.

- trigger/delay.go
- trigger/delay_test.go
Reviewers:
Adds DelayTrigger, which introduces an extensible delay before running another TriggerHandler.
> Closes #81 - Adds DelayTrigger.

- .travis/install.sh
- authentication/cookiemask_test.go
- authentication/inmempwdstore.go
- authentication/minsession.go
- authentication/sessionhandler.go
- monitor/minmonitor.go
Switching from custom errors to proidiot/gone errors.
> Closes #93

- authentication/cookiemask_test.go
- authentication/inmempwdstore_test.go
- config/config.go
- config/config_test.go
- config/pipeline.go
- config/util/validator.go
Switches the Pipeline to be a Resource.
> Closes #104

- README.md
This PR:
- fixes the broken Travis badge
- unifies the badges to shields.io format
- adds Coveralls badge
- adds Linux Foundation CII Best Practices badge
- adds Code Climate badge
- removes Michael's email from README
> Closes #111

- .gitignore
- cmd/pullcord/main.go
Adds a main command that uses `/etc/pullcord.json` by default.
> Closes #121

- .gitignore
- .travis/install.sh
- .travis/tests.sh
- Makefile
> Closes #123

- Makefile
- README.md
- authentication/inmempwdstore.go
- authentication/login_handler.go
- cmd/genhash/main.go
- example/login.json
- util/path_route_adapter.go
Adds an example config that demonstrates how to use a login page.
> Closes #128

- cmd/pullcord/main.go
Adding a basic CLI config option.
> Closes #130

- example/basic.json
Switching basic example config to use default so that only `/favicon.ico` gets a 404.
> Closes #134

- Makefile
Switch coverage file generation to use new recursive capabilities
> Closes #144 - Use new recursive coverage capabilities

- .travis.yml
- .travis/gometalinter.sh
Adds a script to run gometalinter on Travis, but does not (for now) error out on failure.
> Closes #149 - Adds gometalinter to Travis

- authentication/cookiemask.go
- authentication/inmempwdstore.go
- authentication/login_handler.go
- authentication/minsession.go
- monitor/minmonitor.go
- monitor/minmonitor_test.go
- net/basic.go
- net/helper_test.go
- proxy/passthru.go
- trigger/compound.go
- trigger/compound_test.go
- trigger/delay.go
- trigger/ratelimit.go
- trigger/shelltrigger.go
Removing all the unnecessary `else` guards at the tail of always-terminating `if` blocks.
> Closes #153 - Replacing unnecessary else clauses

- cmd/genhash/main.go
Removing redundant type declaration
> Closes #166 - Removing redundant type declaration

- monitor/minmonitor.go
- monitor/minmonitor_test.go
- trigger/compound.go
- trigger/compound_test.go
- trigger/delay.go
- trigger/delay_test.go
- trigger/ratelimit.go
- trigger/ratelimit_test.go
- trigger/shelltrigger.go
- trigger/shelltrigger_test.go
- trigger/sqstrigger.go
- trigger/trigger.go
Switching to a more gorrific name for `trigger.TriggerHandler`
> Closes #165 - Remove stuttering from trigger.TriggerHandler

- authentication/login_handler.go
- authentication/login_handler_test.go
Constifying one of the error strings
> Closes #182 - Constifying one of the error strings

- authentication/login_handler.go
- authentication/minsession_test.go
- config/httpmultiserver.go
- net/basic_test.go
- net/basictls_test.go
There were already a few shadowed variables, and more variables were shadowed after some of the recent golint-related changes.
> Closes #173 - Rework shadowed vars

- .gitignore
- .travis/build.sh
- Makefile.in
- configure
- monitor/minmonitor_test.go
By adding a configure script, it is more obvious how to handle the logic differences between building with and without docker and with and without local golang.
> Closes #177 - Adding configure script to unlock docker-based build

- cmd/pullcord/main.go
- config/httpserver.go
- monitor/minmonitor.go
- trigger/compound.go
- trigger/delay.go
- trigger/ratelimit.go
- trigger/shelltrigger.go
This adds a few more debug messages which illuminated the typo that caused the quick exits.
> Closes #192 - Adding some more debug messages.

- authentication/login_handler.go
- authentication/login_handler_test.go
- net/basictls.go
- net/basictls_test.go
More golint complaining being fixed. This time technical acronyms not being all uppercase.
> Closes #150 -Fixed capitalization of acronyms.

- monitor/minmonitor_test.go
- trigger/compound_test.go
More minor work to please golint.
> Closes #164 -Removing compound iterators as our golint overlord commands.

- config/config_test.go
- config/resource.go
- config/typeregistry.go
- monitor/minmonitor.go
- util/standard_responses.go
Fixes spelling mistakes go report highlighted.
> Closes #207 -Fixing spelling mistakes for issue #207
